shamefullyHoist: true
packages:
  - e2e
  - .
minimumReleaseAge: 10080
overrides:
  '@playwright/test': 1.60.0
  playwright: 1.60.0
  playwright-core: 1.60.0
  react: "npm:@preact/compat@18.3.1"
  react-dom: "npm:@preact/compat@18.3.1"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  msw: true
  sharp: true
