name: Website bug report
description: Template for bug reports about the website
title: "[Website Bug]: "
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: provide steps to reproduce the problem
  - type: textarea
    attributes:
      label: Exception or Error
      description: provide error logs
