name: Fly Deploy

on:
  push:
    branches: [main]

env:
  DOCKER_TAG: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

concurrency:
  group: main-deploy
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "GIT_COMMIT_REF=${{ github.head_ref || github.ref_name }}"
            "PUBLIC_CLOUDINARY_CLOUD_NAME=dssjarn7f"
            "SITE_URL=https://playfulprogramming.com"
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "HOOF_AUTH_TOKEN=${{ secrets.HOOF_AUTH_TOKEN }}"

  deploy_for_prod:
    name: Deploy for prod
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: production
      url: https://playfulprogramming.com
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_WEB_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5
      - name: Deploy app
        run: |
          flyctl deploy --image "$DOCKER_TAG"
      - name: Purge Fastly cache
        env:
          FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
          VARS_FASTLY_SERVICE_ID: ${{ vars.FASTLY_SERVICE_ID }}
        run: |
          # https://www.fastly.com/documentation/guides/full-site-delivery/purging/working-with-surrogate-keys/
          curl -i -X POST "https://api.fastly.com/service/${VARS_FASTLY_SERVICE_ID}/purge/purge-on-deploy" \
            -H "Fastly-Key: $FASTLY_API_KEY" \
            -H 'fastly-soft-purge: 1'
